### ISSUE TITLE
Run pre-commit hooks server side

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1148]
We already discussed with @romainx in https://github.com/jupyter/docker-stacks/pull/1123 pre-commit should be run server-side, to make sure everything will look good in master branch.

An easy way to run all pre-commit hooks:
`pre-commit run --all-files`

Actually, there are already many bashate and few hadolint errors.
So it would be great to fix them and enable server-side checks.

**Comment by romainx** [comment]
Hello,

Now that we have moved to Github actions we should have a look to https://github.com/pre-commit/action.
I'm Ok to work on it and have a clearer way to lint all the files.

Best

**Comment by mathbunnyru** [comment]
Great, but first I will have to fix several bashate errors.

**Comment by romainx** [comment]
@mathbunnyru for bashate errors I suggest the following configuration, it will permit to reduce significantly the number of errors by ignoring the rule `E006`: check for lines longer than 79 columns.

```YAML
- repo: https://github.com/openstack-dev/bashate.git
  rev: 2.0.0
  hooks:
    - id: bashate
      # Ignore
      # - E006: check for lines longer than 79 columns
      args: ['--ignore=E006']
```

The remaining errors will not be too hard to fix nor too risky

```bash
base-notebook/fix-permissions:27:1: E003 Indent not multiple of 4
base-notebook/fix-permissions:27:1: E003 Indent not multiple of 4
base-notebook/fix-permissions:27:1: E003 Indent not multiple of 4
base-notebook/fix-permissions:34:1: E003 Indent not multiple of 4
r-notebook/hooks/run_hook:55:1: E004 File did not end with a newline
5 bashate error(s) found
tensorflow-notebook/hooks/run_hook:45:1: E004 File did not end with a newline
1 bashate error(s) found
minimal-notebook/hooks/run_hook:45:1: E004 File did not end with a newline
1 bashate error(s) found
```
