### ISSUE TITLE
Jupyter Lab Has (Almost) Blank Login Screen

### ISSUE THREAD

**Issue by TheCatster** [jupyter/docker-stacks#1248]
**What docker image you are using?**

Example: `jupyter/datascience-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

```
version: "3"
services:
    jupyterlab:
    image: jupyter/datascience-notebook
    restart: always
    ports:
        - 8888:8888
    volumes:
        - ./jupyter-data:/home/jovyan
        - ./notebooks:/home/jovyan/notebooks
    environment:
        - NB_UID=1000
        - NB_GUID=1000
        - JUPYTER_ENABLE_LAB=yes
        - RESTARTABLE=yes
```

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit https://jupyter.domain.com

**What do you expect to happen?**

Expect to see a login screen, as usual.

**What actually happens?**

This rarely works, for no apparent reason, when I remove the `JUPYTER_ENABLE_LAB` variable, but usually results in a blank screen with a message and textbox to "Enter password or token:". My normal password does not work. I cannot do anything else. Once I remove the variable, it goes back to being a classic notebook, but it does work. This also does not work through an SSH tunnel, so I do not believe it has anything to do with my reverse proxy setup.
