### ISSUE TITLE
How to build datascience-notebook with new version of Pyrthon using docker-compose?

### ISSUE THREAD

**Issue by King-of-penguins** [jupyter/docker-stacks#1252]
I read several comments on how to build a Docker image with a different version of Python: [comment1](https://github.com/jupyter/docker-stacks/issues/1200#issuecomment-745258117) and [comment2](https://github.com/jupyter/docker-stacks/issues/1208#issuecomment-755907605).
These comments recommended using the following argument: `--build-arg PYTHON_VERSION=3.x.x`
In `conda` I found version of Python 3.9.2:
```
conda search python=3.9.2 | head
Loading channels: ...working... done
# Name                       Version           Build  Channel             
python                         3.9.2      hdb3f193_0  pkgs/main 
```
I am trying to use a `docker-compose.yaml` file with the following code:
```
version: "3"
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.9.2
    container_name: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=token
    volumes:
      - /path/to/my/files/with/code:/home/jovyan
    ports:
      - 58888:8888
    restart: unless-stopped
```
and `Dockerfile` with following code:
```
FROM jupyter/datascience-notebook
RUN pip3 install mysql-connector pymysql 
```
This code builds Docker container successfully and I run JupyterLab successfully.
But as soon as in JupyterLab I execute the command:
`!python3 --version`
I am getting output:
`Python 3.8.8`

That is, I wanted to build a Docker image in Python version 3.9.2 and got the original version 3.8.8. I am doing something wrong. How to build a Docker image with Python 3.9.2 using `docker-compose`?
