### ISSUE TITLE
Setting Password instead of token doesn't work in Jupyter Lab

### ISSUE THREAD

**Issue by bwulff** [jupyter/docker-stacks#1287]
**What docker image you are using?**

Docker image: jupyter/datascience-notebook  (bc7cb4e4ab91)

**What complete docker command do you run to launch the container (omitting sensitive values)?**

running as part of a docker-compose:
```
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: my_jupyterlab
    restart: always
    command: jupyter lab /home/jovyan --ip 0.0.0.0 --port 8888 --no-browser
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /data/path/for/jupyter:/home/jovyan
```
(host directory for `/home/jovyan` has uid:gid set as specified for the image, so write access to it from container works)

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888
2. entering the token I obtained from container logs
3. entering a new password
4. (after logging in) log out of the lab
5. going back to login page
6. entering the previously set password

**What do you expect to happen?**

Login with password works.

**What actually happens?**

Login with password doesn't work.

**Additional information**

When trying to set the password, container log says:
```
[I 2021-05-05 10:27:23.040 ServerApp] Wrote hashed password to /home/jovyan/.jupyter/jupyter_server_config.json
```
This seems to be true, since in the file `/data/path/for/jupyter/.jupyter/jupyter_server_config.py` the value of ServerApp.password (the part after `p=` which I think is the password hash) changes when I enter different passwords.
