### ISSUE TITLE
Bad rendering when using a terminal from launcher

### ISSUE THREAD

**Issue by daviddoji** [jupyter/docker-stacks#1318]
**What docker image you are using?**

Using `jupyter/datascience-notebook:lab-3.0.15`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker-compose up -d`

My `compose` file:
```
version: '3' 
services:
# JUPYTER ==> Jupyter Lab instance
  jupyter:
    image: jupyter/datascience-notebook:lab-3.0.15
    container_name: jupyter
    restart: unless-stopped
    networks:
      - programming_network
    volumes:
      - /media/Storage_Server/Programming/Jupyter:/home/jovyan/work
    env_file:
      - .jupyter-env
    labels:
      - traefik.enable=true
      - traefik.http.routers.jupyter.rule=Host(`jupyter.mydomain.com`)
      - traefik.http.routers.jupyter.entrypoints=secure
      - traefik.http.routers.jupyter.tls.certresolver=le
      - traefik.http.services.jupyter.loadbalancer.server.port=8888
```

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Starting an instance of jupyter.mydomain.com
2. Start a simple terminal
3. Get the following:
![2021-05-21_21-18](https://user-images.githubusercontent.com/4411314/119187839-63956680-ba69-11eb-8a20-d25c93378aae.png)

**What do you expect to happen?**

When I open a terminal from portainer, I see a proper rendering: 
![2021-05-21_21-19](https://user-images.githubusercontent.com/4411314/119188006-9d666d00-ba69-11eb-802d-de2233c05de4.png)

**What actually happens?**

The rendering of a terminal is totally messed-up from the launcher. I can still use it from Portainer, but still it'd good to have that fixed.

Notebooks have no problem at all with the rendering.

Thanks in advance.
