### ISSUE TITLE
Unexpected console message from IVY and spark

### ISSUE THREAD

**Issue by mbalduini** [jupyter/docker-stacks#1423]
Description
* used docker image: jupyter/pyspark-notebook:b9f6ce795cfc
* Started up via docker-compose:
```
version: '3'
services:
  qc-platform:
    image: jupyter/pyspark-notebook:b9f6ce795cfc
    ports:
      - 8888:8888
    environment:
      - GRANT_SUDO=yes 
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=test
    user: root
    restart: unless-stopped
```
* Additional Information: Downgraded from java 11 to Java 8

Running a simple cell to create a spark session (see code below) annoying message from Ivy (related to packages config) and spark start to be printed on console.

![Screenshot 2021-08-09 at 13 03 56](https://user-images.githubusercontent.com/4280101/128697128-684aedcd-f48e-4efc-a38f-09b5f568063e.png)

I tried to change che log4j configuration for spark and the `logging` lib to set the global logging level with no results.

Any help in removing completely the messages in the picture?
