### ISSUE TITLE
jupyter/r-notebook:r-4.1.2 uses r-3.6.3 instead r-4.1.2

### ISSUE THREAD

**Issue by Shanduur** [jupyter/docker-stacks#1582]
Hi! Thanks for using the Jupyter Docker Stacks.

Please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

`jupyter/r-notebook:r-4.1.2`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker compose up`

```yml
services:
  jupyter_r:
    image: jupyter/r-notebook:r-4.1.2
    container_name: jupyter-r
    ports:
      - 8080:8888
    volumes:
      - .:/home/jovyan/work/
    user: root
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "passw0rd"
      GRANT_SUDO: "yes"
```

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit <http://localhost:8080>
2. Start an R console or Terminal
3. Observe the R version

**What do you expect to happen?**

```
(base) jovyan@d22dd7cd9b08:~$  R --version
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
```

**What actually happens?**

```
(base) jovyan@d22dd7cd9b08:~$ R --version
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
```
