### ISSUE TITLE
[BUG] start by singleuser doesn't has bashrc properly set in user folder

### ISSUE THREAD

**Issue by unkcpz** [jupyter/docker-stacks#1848]
### What docker image(s) are you using?

minimal-notebook

### OS system and architecture running docker image

Ubuntu 18.04 amd64

### What Docker command are you running?

```yaml
---
singleuser:
    image:
        name: "docker.io/jupyter/minimal-notebook"      
        tag: "python-3.9.13"
        pullPolicy: "Always"
    extraEnv:
        DOCKER_STACKS_JUPYTER_CMD: "notebook"
        #JUPYTERHUB_SINGLEUSER_APP: "notebook.notebookapp.NotebookApp"
    storage:
        dynamic:
            storageClass: aiidalab-storage
...
```

### How to Reproduce the problem?

1. open the container spawned (I use microk8s in my deployment). 
2. It is still running the lab mode, which I expect the notebook since I set `DOCKER_STACKS_JUPYTER_CMD=notebook`
3. Also run `ls -al`, there is no `.bashrc` in the user home folder.

### Expected behavior

The entity start at notebook mode and the `.bashrc` setting is not being wiped out.

### Actual behavior

It is all fine if I run the container without `JUPYTHERHUB_API_TOKEN` by docker run in my local machine. But spawn the user by spawner, the `JUPYTERHUB_API_TOKEN` will shift to `start-singleuser.sh` (as https://github.com/jupyter/docker-stacks/blob/f60eda163f9164e5264335933dfeddd04323450c/base-notebook/start-notebook.sh#L11-L14 here indicated).

Is there anything run in my `singleuser` setting?
