### ISSUE TITLE
[BUG] - Build fails on fix-permissions script after scipy dependencies install

### ISSUE THREAD

**Issue by dasantonym** [jupyter/docker-stacks#1866]
### What docker image(s) are you using?

scipy-notebook

### Host OS system and architecture running docker image

Ubuntu 22.04 / Kaniko Build in GitLab Runner

### What Docker command are you running?

I am building a Docker image based on:

`FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04`

Then, I am concatenating the contents of (in this order):

- `docker-stacks-foundation/Dockerfile`
- `base-notebook/Dockerfile`
- `minimal-notebook/Dockerfile`
- `scipy-notebook/Dockerfile`

The commit hash for my docker-stacks dir is `1387ff70e30635aa5e75c95cebee041f8d03acbf`

### How to Reproduce the problem?

I would think that concatenating the Dockerfiles as stated above and then running this in a GitLab runner with Kaniko as below, should fail similarly.

```yaml
deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/.build --dockerfile $CI_PROJECT_DIR/.build/Dockerfile --destination $CI_REGISTRY/library/gpu-jupyter:$CI_COMMIT_BRANCH
```

### Command output

This is the error in the log:

```bash session
chgrp: changing group of '/opt/conda/lib/R': Operation not permitted
chgrp: changing group of '/opt/conda/lib/R/etc': Operation not permitted
chmod: changing permissions of '/opt/conda/lib/R': Operation not permitted
chmod: changing permissions of '/opt/conda/lib/R/etc': Operation not permitted
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

This error happens here: https://github.com/jupyter/docker-stacks/blob/main/scipy-notebook/Dockerfile#L29

Full log output can be found here: https://pastebin.com/MXcN8av6

### Actual behavior

The exact same build works on my M1 MacBook with:

`docker buildx build --platform linux/amd64 --load -t gpu-jupyter .build/`

But it fails when I build on GitLab.

### Anything else?

I don't know if this is the right place because it is not universally reproducible and, thus, not specifically an issue with the docker stacks. Still, maybe someone has an idea why these folders end up with those permissions. Or maybe how to debug this further.

There is nothing custom going on before the error. It is just all Dockerfiles (without their FROM lines) concatenated.

### Latest Docker version

- [X] I've updated my Docker version to the latest available and the issue still persists
