### ISSUE TITLE
[BUG] - Generating new user for token-authenticated request keeps appearing when token auth is disabled

### ISSUE THREAD

**Issue by ahlag** [jupyter/docker-stacks#1892]
### What docker image(s) are you using?

pyspark-notebook

### Host OS system and architecture running docker image

MacOS

### What Docker command are you running?

Running these with docker compose - `docker compose up`.
```
version: '3'
services:
  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
    command: "start.sh jupyter lab --NotebookApp.token='' --NotebookApp.password=''"
    networks:
      - network

networks:
  network:
    name: network
```

### How to Reproduce the problem?

1. Run `docker compose up` in the directory that has the above yaml.

### Command output

```bash session
Connecting to kernel e9c0749c-006d-4e25-bc82-77cbf5dc9d0c.
Connecting to kernel e9c0749c-006d-4e25-bc82-77cbf5dc9d0c.
Connecting to kernel e9c0749c-006d-4e25-bc82-77cbf5dc9d0c.
Generating new user for token-authenticated request: 7b68a45cafb241cca9084ff2f8f01622
Generating new user for token-authenticated request: 691150522f9d472abc41be4d553229bd
Generating new user for token-authenticated request: 96bc5cde3369469a8c0d304f2ca34c1e
```
```


### Expected behavior

We do not want Generating new user for token-authenticated request: 96bc5cde3369469a8c0d304f2ca34c1e to appear.

### Actual behavior

Generating new user for token-authenticated request: keeps appearing.

### Anything else?

_No response_

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists
