### ISSUE TITLE
[ENH] - Document correct way to persist conda packages

### ISSUE THREAD

**Issue by laundmo** [jupyter/docker-stacks#1959]
### What docker image(s) is this feature applicable to?

base-notebook

### What change(s) are you proposing?

Documenting a "blessed" way of persisting installed python packages, such that they are not removed after the container is recreated.

Ideally this should be a way which doesn't require persisting the packages automatically installed by the container

### How does this affect the user?

As seen in
- #1836

its not currently obvious how to correctly do this. Finding this issue is also not easy.

a documentation section for this would help users achieve this quickly without a lot of searching, and allow maintainers to choose one way of persisting python packages (entire conda env or just relevant folders? docker host mount or volume?)

**Comment by bjornjorgensen** [comment]
I use a `docker-compose.yml` file 
```
version: '3.7'
services:
  my-service:
    image: jupyter/base-notebook:latest
    volumes:
      - myvolume:/opt/conda
volumes:
  myvolume:

```
