### ISSUE TITLE
Add an environment variable to define some additional Python package to install

### ISSUE THREAD

**Issue by SuperPat45** [jupyter/docker-stacks#2297]
### What docker image(s) is this feature applicable to?

scipy-notebook

### What change(s) are you proposing?

Add an environment variable to define some additional Python packages to install

### How does this affect the user?

This will add more flexibility

### Anything else?

For example, something like:
```
services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      - "ADDITIONAL_PYTHON_PACHAGES=xlsxwriter docx"
      - "JUPYTER_ENABLE_LAB=yes"
      - "JUPYTER_TOKEN=sk-1234"
    restart: unless-stopped
```
