### ISSUE TITLE
unknown docker network

### ISSUE THREAD

**Issue by MAliNaqvi** [jupyter/docker-stacks#318]
I am constantly getting the following error:

```
Exception: Unknown docker network 'jupyterhub_network'. Did you create it with 'docker network create <name>' and did you pass network_mode=<name> in extra_kwargs?
```

I already have a docker network which I created using: 

```
docker network create jupyterhub_network
```

This network is also part of my config in `jupyterhub_config.py` file here is the network configuration:

```
network_name = 'jupyterhub_network'                                             
c.DockerSpawner.use_internal_ip = True                                          
c.DockerSpawner.network_name = network_name                                     
c.DockerSpawner.extra_host_config = { 'network_mode': network_name } 
```

I run jupyterhub using:

```
docker run  \
        -it -p 443:443 \
        -p 8000:8000 \
        -v "/var/run/docker.sock:/var/run/docker.sock:rw" \
        --name jupyterhub \
        --network jupyterhub_network \
        jupyter/jupyterhub jupyterhub
```

**Comment by parente** [comment]
This issue has been inactive for some time. @MAliNaqvi please reopen the issue if you looked at the jupyterhub-deploy-docker repository and are still facing problems.

**Comment by mueslo** [comment]
I'm having the exact same issue, so I'd be grateful if you could reopen this. I have looked at the reference jupyterhub docker deployment, which is basically what I copied.

My `docker-compose.yml` looks as follows, 
```
services:
  jupyterhub:
    build: config/jupyterhub/build/
    hostname: jupyterhub
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /some/dir/config/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    environment:
      - TZ=Europe/Berlin
      - DOCKER_NETWORK_NAME=jupyterhub
    ports:
      - 8000:8000
    networks:
      - jupyterhub
networks:
  jupyterhub:
    external:
      name: jupyterhub

```

my `jupyterhub_config.py` contains
```
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
import os
network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.network_name = network_name
c.DockerSpawner.extra_host_config = {'network_mode': network_name}
```

And the network was created on the docker host and is joined by the jupyterhub container:

```
$docker network inspect jupyterhub
[
    {
        "Name": "jupyterhub",
        "Id": "a5b5988062a86a90a07e70149bb5909652fa7916ad14a4833a42c65fa6b21e2b",
        "Created": "2018-07-20T18:49:56.122820709+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.22.0.0/16",
                    "Gateway": "172.22.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "e2d55d3ad00aceac12ac23ff4e1a8b5346d8fa83225063c234bc2d356fefa28a": {
                "Name": "services_jupyterhub_1",
                "EndpointID": "77635a92e50b348ed57c0e5f0c5b3e264090357b631e44cfc3e37ffc79554967",
                "MacAddress": "02:42:ac:16:00:02",
                "IPv4Address": "172.22.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```
