### ISSUE TITLE
Jupyter on kubernetes dead kernel error

### ISSUE THREAD

**Issue by jerryjung** [jupyter/docker-stacks#337]
**What docker image you are using?**
`jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**
kubectl create -f kubernetes/jupyter-kubernetes.yaml

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jupyter-notebook
  template:
    metadata:
      labels:
        component: jupyter-notebook
    spec:
      containers:
        - name: jupyter
          image: jupyter/base-notebook:latest
          command: ["start-notebook.sh"]
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 100m

---

kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
  selector:
    component: jupyter-notebook
```

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://ip-address:30088
2. Start an Python noteobok
3. No kernel.

**What do you expect to happen?**

Example: connected

**What actually happens?**

Example: Dead Kernel error occurs.
The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

![screen shot 2017-02-02 at 8 03 33 pm](https://cloud.githubusercontent.com/assets/4940963/22546974/b2f862a2-e982-11e6-9964-21c299036a53.png)

log message is below.
[D 08:26:37.026 NotebookApp] 304 GET /static/components/MathJax/extensions/Safe.js?rev=2.6.0 (172.16.11.0) 1.21ms
[D 08:26:37.094 NotebookApp] Found kernel python3 in /opt/conda/share/jupyter/kernels
[D 08:26:37.095 NotebookApp] Starting kernel: ['/opt/conda/bin/python', '-m', 'ipykernel', '-f', '/home/metatron/.local/share/jupyter/runtime/kernel-74fc4a1a-d248-42e4-8925-8dcbc7d0099e.json']
[D 08:26:37.102 NotebookApp] Connecting to: tcp://127.0.0.1:40993
[I 08:26:37.103 NotebookApp] Kernel started: 74fc4a1a-d248-42e4-8925-8dcbc7d0099e
[D 08:26:37.103 NotebookApp] Kernel args: {'kernel_name': 'python3', 'cwd': '/home/metatron/work'}
[D 08:26:37.104 NotebookApp] 201 POST /api/sessions (172.16.11.0) 31.27ms
[D 08:26:37.107 NotebookApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?_=1486023996816 (172.16.11.0) 1.60ms
[D 08:26:37.131 NotebookApp] Initializing websocket connection /api/kernels/74fc4a1a-d248-42e4-8925-8dcbc7d0099e/channels
[D 08:26:37.134 NotebookApp] Requesting kernel info from 74fc4a1a-d248-42e4-8925-8dcbc7d0099e
[D 08:26:37.134 NotebookApp] Connecting to: tcp://127.0.0.1:37472
[I 08:26:40.105 NotebookApp] KernelRestarter: restarting kernel (1/5)
[D 08:26:40.106 NotebookApp] Starting kernel: ['/opt/conda/bin/python', '-m', 'ipykernel', '-f', '/home/metatron/.local/share/jupyter/runtime/kernel-74fc4a1a-d248-42e4-8925-8dcbc7d0099e.json']
[D 08:26:40.111 NotebookApp] Connecting to: tcp://127.0.0.1:40993
[I 08:26:43.115 NotebookApp] KernelRestarter: restarting kernel (2/5)
[D 08:26:43.116 NotebookApp] Starting kernel: ['/opt/conda/bin/python', '-m', 'ipykernel', '-f', '/home/metatron/.local/share/jupyter/runtime/kernel-74fc4a1a-d248-42e4-8925-8dcbc7d0099e.json']
[D 08:26:43.120 NotebookApp] Connecting to: tcp://127.0.0.1:40993
[I 08:26:46.120 NotebookApp] KernelRestarter: restarting kernel (3/5)
[D 08:26:46.121 NotebookApp] Starting kernel: ['/opt/conda/bin/python', '-m', 'ipykernel', '-f', '/home/metatron/.local/share/jupyter/runtime/kernel-74fc4a1a-d248-42e4-8925-8dcbc7d0099e.json']
[D 08:26:46.126 NotebookApp] Connecting to: tcp://127.0.0.1:40993
[W 08:26:47.136 NotebookApp] Timeout waiting for kernel_info reply from 74fc4a1a-d248-42e4-8925-8dcbc7d0099e
[D 08:26:47.138 NotebookApp] Opening websocket /api/kernels/74fc4a1a-d248-42e4-8925-8dcbc7d0099e/channels
[D 08:26:47.138 NotebookApp] Connecting to: tcp://127.0.0.1:37472
[D 08:26:47.138 NotebookApp] Connecting to: tcp://127.0.0.1:44841
[D 08:26:47.139 NotebookApp] Connecting to: tcp://127.0.0.1:57383
[I 08:26:49.128 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 74fc4a1a-d248-42e4-8925-8dcbc7d0099e restarted
[D 08:26:49.130 NotebookApp] Starting kernel: ['/opt/conda/bin/python', '-m', 'ipykernel', '-f', '/home/metatron/.local/share/jupyter/runtime/kernel-74fc4a1a-d248-42e4-8925-8dcbc7d0099e.json']
[D 08:26:49.135 NotebookApp] Connecting to: tcp://127.0.0.1:40993
