### ISSUE TITLE
Use install_github from devtools

### ISSUE THREAD

**Issue by danfowler** [jupyter/docker-stacks#411]
**What docker image you are using?**

`jupyter/r-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

```
 jupyter:
    container_name: jupyter
    ports:
      - 8888:8888
    image: jupyter/r-notebook
    volumes:
      - /mnt/data/notebooks:/home/jovyan/work
    entrypoint:
      - "start-notebook.sh"
      - "--NotebookApp.token=''"
    environment:
      GRANT_SUDO: "yes"
    restart: always
```

**What steps do you take once the container is running to reproduce the issue?**

![screen shot 2017-06-30 at 12 08 53](https://user-images.githubusercontent.com/772616/27721781-f48f9752-5d8c-11e7-845d-354c64e0c4df.png)

**What do you expect to happen?**

Be able to use library installed via `install_github`.

**What actually happens?**

Failure as indicated in screenshots.
