### ISSUE TITLE
docker-stacks in kubernetes --user root config

### ISSUE THREAD

**Issue by luck02** [jupyter/docker-stacks#477]
Hi! Thanks for using Jupyter's docker-stacks images.

If you are requesting a library upgrade or addition in one of the existing images, please state the desired library name and version here and disregard the remaining sections.

More of a question than an upgrade request.

We're running a kubernetes based infra and I'd like to be able to provide quick and simple pyspark style notebooks for my users.

I whipped this up:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-pod-jupyter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: jupyter-test
    spec:
      containers:
        - name: test-container-jup
          image: jupyter/all-spark-notebook
          resources:
            requests:
              cpu: 8
              memory: 30G
            limits:
              cpu: 8
              memory: 30G
          env:
          - name: GRANT_SUDO
            value: "yes"
```

And it worked, until I needed root to modify the image in place (a pre-requisite... I generally make modifications, test them and then codify the changes).

I see the instructions in the notebooks state:

> -e GRANT_SUDO=yes - Gives the jovyan user passwordless sudo capability. Useful for installing OS packages. For this option to take effect, you must run the container with --user root. (The start-notebook.sh script will su jovyan after adding jovyan to sudoers.) You should only enable sudo if you trust the user or if the container is running on an isolated host.

I don't think there's a way to suit that requirement in Kubernetes (at least not to my knowledge).  If there is great, if not has anyone else run into this?  

If not is there interest in making this feature (root user) available via an environment variable or some other mechanism?  IE a command arg in kubernetes.

I've done a bit of digging into the various start scripts, presumably there's a mechanism to call them with the correct setup, but it doesn't seem overly documented or intended.
