### ISSUE TITLE
happens lots of jovyan user password problem

### ISSUE THREAD

**Issue by hero0926** [jupyter/docker-stacks#481]
**What docker image you are using?**

jupyter/pyspark-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**

my docker-compose file

```
image: jupyter/pyspark-notebook
        ports:
            - "8888:8888"
            - "4040-4080:4040-4080"
        volumes:
           - ./notebooks:/home/jovyan/work/notebooks
        environment :
           - GRANT_SUDO="yes"
        user:
          "root"
```

**What steps do you take once the container is running to reproduce the issue?**

1. Trying to make integration with zeppelin
2. Cause zeppelin notebook ui connection refused error(with no error in zeppelin logs)
3. want to use sudo command(with mv, apt-get ...etc)
4. and get demand on paswword for jovyan(who is he?)

**What do you expect to happen?**

Can We get password for jovyan? It could be much easier than grant root things for docker newbies.
or are we possible to use any sudo command with docker-compose or running exec command?
and who the hell is jovyan?
