### ISSUE TITLE
Cannot access through https://ip:port

### ISSUE THREAD

**Issue by OnlyBelter** [jupyter/docker-stacks#563]
I am using docker-compose to set `jupyter/datascience-notebook` up. My `docker-compose.yml` like below:
```
version: '3'

services:
  jupyterlab:
    image: jupyter/datascience-notebook
    # environment:
    #   - "TZ=Asia/Shanghai"
    command: /bin/bash -c "start.sh jupyter lab --NotebookApp.keyfile=/etc/ssl/notebook/mykey.key --NotebookApp.certfile=/etc/ssl/notebook/mycert.pem --NotebookApp.port=6000 --NotebookApp.password=u'sha1:9f3677c93909:e3f84a329f8b5d6f2390ccba682cac5d0f7e9b83'"
    volumes:
      - ./config/ssl:/etc/ssl/notebook
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6000:8888
```

My website is hosted on `alibabacloud`, https://account.alibabacloud.com/. Because this host has other apps, I cannot change the whole web apps to `https` connection. I only got `mycert.pem` and `mykey.key` by `openssl`.
I run `docker-compose` through `docker-compose up`, I got the following information:
```
Starting jupyterlab_jupyterlab_1 ... done
Attaching to jupyterlab_jupyterlab_1
jupyterlab_1  | Container must be run with group root to update passwd file
jupyterlab_1  | Executing the command: jupyter lab --NotebookApp.keyfile=/etc/ssl/notebook/mykey.key --NotebookApp.certfile=/etc/ssl/notebook/mycert.pem --NotebookApp.port=6000 --NotebookApp.password=usha1:9f3677c93909:e3f84a329f8b5d6f2390ccba682cac5d0f7e9b83
jupyterlab_1  | [I 20:39:58.196 LabApp] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
jupyterlab_1  | [I 20:39:58.197 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
jupyterlab_1  | [I 20:39:58.204 LabApp] Serving notebooks from local directory: /home/jovyan
jupyterlab_1  | [I 20:39:58.204 LabApp] 0 active kernels
jupyterlab_1  | [I 20:39:58.205 LabApp] The Jupyter Notebook is running at:
jupyterlab_1  | [I 20:39:58.205 LabApp] https://[all ip addresses on your system]:6000/
jupyterlab_1  | [I 20:39:58.205 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```
Then I try to access JupyterLab through `https:my_ip_address:6000`, but I always got `Unable to access this website, ...`

**Comment by parente** [comment]
The `Unable to access this website` make me believe the problem is with the app configuration on alibabacloud.com.

I'm not familiar with alibabacloud.com and how it maps external ports to your application. Is port 6000 allowed?

**Comment by OnlyBelter** [comment]
Now I can access through http://ip:port (eg: http://192.168.201.33:8888) in our local area network by using below configration:
```
version: '3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    restart: on-failure
    volumes:
      - /mnt/home/belter/github/jupyter-note:/mnt/notebook
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8888:8888
    command: /bin/bash -c "jupyter lab --no-browser --ip=0.0.0.0 --notebook-dir=/mnt/notebook"
```

But I still cannot access it through public ip (our web server, similar to AWS) with the same configuration.

By the way, is there a way to connect this port, like `8888`, to my domain and serve it through `nginx`?
