### ISSUE TITLE
adding cvxopt to scipy-notebook using docker-compose

### ISSUE THREAD

**Issue by daviddoji** [jupyter/docker-stacks#883]
**What docker image you are using?**

`jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

I'm using a docker-compose.yml. The part for jupyter is this one:
```
jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    restart: unless-stopped
    networks:
      - web
    environment:
      - .jupyter-env
    volumes:
      - /media/HDD1/Jupyter/data/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_con$
      - /media/HDD1/Jupyter/notebooks:/home/jovyan
    labels:
      - traefik.backend=jupyter
      - traefik.frontend.rule=Host:jupyter.mydomain.com
      - traefik.port=8888
      - traefik.enable=true
```

The .jupyter-env file:

`pip install cvxopt`

**What steps do you take once the container is running to reproduce the issue?**

The notebook runs ok, but the library cvxopt is not imported

**What do you expect to happen?**

`import cvxopt`

**What actually happens?**

```
import cvxopt

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-01f8b2e0f668> in <module>
----> 1 import cvxopt

ModuleNotFoundError: No module named 'cvxopt'
```

I tried to follow what it's suggested in the docs:
```docker build --rm -t jupyter/scipy-notebook .```

but it seems that there are permission issues with another file:
```error checking context: 'no permission to read from '/home/david/docker/bitwarden/data/rsa_key.der''.```
