### ISSUE TITLE
A Suggestion on Creating Linux User Password

### ISSUE THREAD

**Issue by LY1806620741** [jupyter/docker-stacks#931]
Hi , When i use my docker-compose
```
version: "2"
services:
    jupyter:
        image: jupyter/base-notebook
        ports:
            - "8888:8888"
        restart: always
```
Then run a base jupyter service on my computer, and now i need ``` pip install h3 ``` use jupyter terminals. But it depend on cc, make, and cmake. I can't ```which``` them on the container. So, I must i use ```sudo apt-get install cmake```.  So you can be imagined. I don't have root and jovyan's password. This mean i can't install h3 on the base-jupyter docker.

**Comment by sfo** [comment]
If you need an image with additional features, it would probably be the preferred way to build a derived image.
Just change you docker-compose script like so:
```yml
version: "2"
services:
    jupyter:
        image: h3-notebook
        ports:
            - "8888:8888"
        restart: always
```
Then, create a new dockerfile as `h3-notebook/Dockerfile`. Content could be for example:
```docker
FROM jupyter/base-notebook

USER root

RUN apt update && \
    apt install -y cmake && \
    rm -rf rm -rf /var/lib/apt/lists/*

USER $NB_UID

RUN pip install h3
```
To build it, simply run `docker-compose build`.

For more details on how to configure the docker compose build step, see the [documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#build)
