### ISSUE TITLE
org.apache.spark.api.python.PythonException; local class incompatible

### ISSUE THREAD

**Issue by luminousmen** [jupyter/docker-stacks#945]
I'm trying to use jupyter/all-spark-notebook with an external standalone spark cluster. Got the error while doing a simple script:

```import os
import pyspark
conf = pyspark.SparkConf()

conf.setMaster("spark://172.19.0.2:7077")
sc = pyspark.SparkContext(conf=conf)
rdd = sc.parallelize(range(1000))
rdd.take(3)
```
Error:
```java.io.InvalidClassException: org.apache.spark.api.python.PythonException; local class incompatible: stream classdesc serialVersionUID = 5540028395182668829, local class serialVersionUID = -216573626675865439```

I'm using docker images as part of docker-compose, usage below:
```
jupyter:
    build: ./docker/jupyter/
    ports:
      - "8888:8888"
    network_mode: host
    pid: "host"
    environment:
      - "TINI_SUBREAPER=true"
      - "APACHE_SPARK_VERSION=2.4.3"
```
Thanks in advance!
